// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-NtUKd8iDdnv56KpI68iMaw5JfS5-1OM',
    appId: '1:509736648186:web:969889b094b66419cd3843',
    messagingSenderId: '509736648186',
    projectId: 'prjpab2-si61-2327240082',
    authDomain: 'prjpab2-si61-2327240082.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240082.firebasestorage.app',
    measurementId: 'G-7PP1CJ55K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRKaJRMC5ydntZK1z26c58GwocVYeqoE',
    appId: '1:509736648186:android:d3b778620f1da779cd3843',
    messagingSenderId: '509736648186',
    projectId: 'prjpab2-si61-2327240082',
    storageBucket: 'prjpab2-si61-2327240082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nAdA9aUYf5HgW0kVsPKf6DMgXftKXpw',
    appId: '1:509736648186:ios:4e6c376bc422ded6cd3843',
    messagingSenderId: '509736648186',
    projectId: 'prjpab2-si61-2327240082',
    storageBucket: 'prjpab2-si61-2327240082.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0nAdA9aUYf5HgW0kVsPKf6DMgXftKXpw',
    appId: '1:509736648186:ios:4e6c376bc422ded6cd3843',
    messagingSenderId: '509736648186',
    projectId: 'prjpab2-si61-2327240082',
    storageBucket: 'prjpab2-si61-2327240082.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-NtUKd8iDdnv56KpI68iMaw5JfS5-1OM',
    appId: '1:509736648186:web:bfb682cb11882301cd3843',
    messagingSenderId: '509736648186',
    projectId: 'prjpab2-si61-2327240082',
    authDomain: 'prjpab2-si61-2327240082.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240082.firebasestorage.app',
    measurementId: 'G-X022HG2EQE',
  );
}
