// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiY-RF61PquEyd-d9jFqDPDbm6bUilCSQ',
    appId: '1:17705210064:web:48db2885dfcf3c37ccced5',
    messagingSenderId: '17705210064',
    projectId: 'tes1-2893c',
    authDomain: 'tes1-2893c.firebaseapp.com',
    storageBucket: 'tes1-2893c.firebasestorage.app',
    measurementId: 'G-1VCN22RJHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsd6Db-q7aH-ac6emMM-LTusM2xnES48',
    appId: '1:17705210064:android:6628c837ed517567ccced5',
    messagingSenderId: '17705210064',
    projectId: 'tes1-2893c',
    storageBucket: 'tes1-2893c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqwyWBKo2ZAlmh6X9azck7aRHK4AJann8',
    appId: '1:17705210064:ios:36d9213c16c0e957ccced5',
    messagingSenderId: '17705210064',
    projectId: 'tes1-2893c',
    storageBucket: 'tes1-2893c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqwyWBKo2ZAlmh6X9azck7aRHK4AJann8',
    appId: '1:17705210064:ios:36d9213c16c0e957ccced5',
    messagingSenderId: '17705210064',
    projectId: 'tes1-2893c',
    storageBucket: 'tes1-2893c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiY-RF61PquEyd-d9jFqDPDbm6bUilCSQ',
    appId: '1:17705210064:web:f57d92df145bfce1ccced5',
    messagingSenderId: '17705210064',
    projectId: 'tes1-2893c',
    authDomain: 'tes1-2893c.firebaseapp.com',
    storageBucket: 'tes1-2893c.firebasestorage.app',
    measurementId: 'G-9BZXZ5RJ6W',
  );

}